### ISSUE TITLE
server

### ISSUE THREAD

**Issue by lihaoqiang001** [AmosWang0626/mall#2]
问下：你的server模块删除了？

**Comment by AmosWang0626** [comment]
> 问下：你的server模块删除了？

删除了，最近 master 在重构这块，准备使用阿里的nacos，你可以看下 eureka 分支。
[eureka](https://github.com/AmosWang0626/mall/tree/eureka)

**Comment by lihaoqiang001** [comment]
好的，看到了，感谢！点赞作者！

**Comment by lihaoqiang001** [comment]
> > 问下：你的server模块删除了？
> 
> 删除了，最近 master 在重构这块，准备使用阿里的nacos，你可以看下 eureka 分支。
> [eureka](https://github.com/AmosWang0626/mall/tree/eureka)

**Comment by lihaoqiang001** [comment]
> > 问下：你的server模块删除了？
> 
> 删除了，最近 master 在重构这块，准备使用阿里的nacos，你可以看下 eureka 分支。
> [eureka](https://github.com/AmosWang0626/mall/tree/eureka)

好的，看到了，感谢！点赞作者！
